"""
Dynamic Programming — "Can I break this into overlapping subproblems where an earlier decision affects what's optimal later, and do I need an optimal value or a count (not just yes/no reachability)?"
Trees — "Is the input a tree, and does the answer at each node depend on combining results from its children?"
Graphs — "Is there a network of nodes/edges (explicit or implicit), and am I asking about reachability, shortest path, ordering, or connectivity?"
Two Pointers — "Is the array sorted (or sortable), and am I looking for a pair/triplet satisfying a condition — without needing to preserve original indices?"
Sliding Window — "Do I need a CONTIGUOUS subarray/substring, and does growing/shrinking it change validity in one consistent direction (monotonically)?"
Hash Maps — "Do I need fast 'have I seen this / how many times' lookups, regardless of position or order?"
Prefix Sums — "Do I need repeated range-sum queries, or subarray-sum-equals-target counting — especially if negative numbers rule out sliding window?"
Intervals — "Is the input a list of (start, end) ranges I need to merge, insert into, or count overlaps of?"
Linked Lists — "Am I directly rewiring .next/.prev pointers, rather than indexing into an array?"
Backtracking — "Do I need to enumerate ALL valid combinations/arrangements/paths, trying a choice and undoing it if it doesn't pan out?"
Binary Search — "Is there a sorted array to search, OR a range of possible answers where 'does this candidate work' behaves monotonically as the candidate increases?"
Stacks / Monotonic Stack — "Do I need the nearest greater/smaller element, or to match nested/paired structures?"
Heaps — "Do I repeatedly need the current min/max, or the top-K, from a collection that keeps changing?"
"""